- name: rabbitmq configuration
  hosts: rabbitmq
  become: yes
  tasks:
  - name: configure yum repo
    ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash

  - name: configure yum repos fir rabbitmq
    ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash
     
  - name: install rabbitmq
    ansible.builtin.package:
      name: rabbitmq-server
      state: present

  - name: enable and start the rabbitmq-server
    ansible.builtin.service:
      name: rabbitmq-server
      state: started
      enabled: yes
