- name: redis configuration
  hosts: redis
  become: yes
  tasks: 
  - name: Download url
    ansible.builtin.shell: dnf install https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y

  - name: enable module
    ansible.builtin.shell: dnf module enable redis:remi-6.2 -y
      