- name: shipping configuration
  hosts: shipping
  become: yes
  tasks:
  - name: install maven
    ansible.builtin.package:
      name: maven
      state: present

  - name: user creation
    ansible.builtin.user:
      name: roboshop

  - name: create a app directory
    ansible.builtin.file:
      path: /app          
      state: directory

  - name: Download the application code
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/shipping.zip
      dest: /tmp

  - name: unzip the content
    ansible.builtin.unarchive:
      src: /tmp/shipping.zip
      dest: /app
      remote_src: yes

  - name: install maven dependencies
    ansible.builtin.command: mvn clean package
    args:
      chdir: /app

  - name: Move the src file to dest
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
    args:
      removes: target/shipping-1.0.jar
      creates: shipping.jar

  - name: copy shipping.service file
    ansible.builtin.copy:
      src: shipping.service
      dest: /etc/systemd/system/shipping.service  

  - name: reload the daemon
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: enable and start the shipping
    ansible.builtin.service:
      name: shipping
      state: started
      enabled: yes

  - name: install mysql client
    ansible.builtin.package:
      name: mysql
      state: present

  - name: load  data
    ansible.builtin.shell: mysql -h mysql.jaya123.shop -uroot -pRoboShop@1 < /app/schema/shipping.sql

  - name: restart shipping
    ansible.builtin.service:
      name: shipping
      state: restarted  
      enabled: yes









