- name: user configuration
  hosts: user
  become: yes 
  tasks:
  - name: disable and enable node-js
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

  - name: install node-js
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: create a roboshop user
    ansible.builtin.user:
      name: roboshop

  - name: create a app directory
    ansible.builtin.file:
      path: /app          
      state: directory

  - name: Download the application code
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/user.zip
      dest: /tmp

  - name: unzip the content
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes

  - name: install npm dependencies
    ansible.builtin.command: npm install
    args:
      chdir: /app

  - name: copy user service file
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service    

  - name: reload the daemon
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: enable and restart the user
    ansible.builtin.service:
      name: user
      state: restarted
      enabled: yes

