- name: web configuration
  hosts: web
  become: yes
  tasks: 
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present

  - name: enable and start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
  

    